name = "cognigy-socketio-client"
type = "webpack"
account_id = ""  # Your Cloudflare account ID
workers_dev = true

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
workers_dev = false

[build]
command = "npm run build"
output_dir = "dist"
